
# Enable displaying emojis
# enableEmoji = true


# disclaimer = "Opinions listed here are my own and not representative of any of my employers, past, future, and/or present."
# #
# [params.plausible]
# enable = true
# domain = "tobiacavalli.com"
# outbound_link = true
# file_downloads = true
# debug = false
# gitstar = false
